volumes:
  db_data:
  prom_data:

networks:
  api_net:
      driver: bridge
  metrics:
    driver: bridge

services:
  api:
    extends:
      file: compose.yaml
      service: api
    networks:
      - metrics

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./metrics/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    networks:
      - metrics

  household_budget_db:
    extends:
      file: compose.yaml
      service: household_budget_db
